# Generated by Django 3.2.6 on 2021-08-03 15:35

from django.contrib.auth.models import Group, Permission
from django.db import migrations

def create_default_groups(apps, schema_editor):
    principal, created = Group.objects.get_or_create(name='Principals')
    # # Class
    # principal.permissions.add(Permission.objects.get(name='Can add squad'))
    # principal.permissions.add(Permission.objects.get(name='Can change squad'))
    # principal.permissions.add(Permission.objects.get(name='Can delete squad'))
    # principal.permissions.add(Permission.objects.get(name='Can view squad'))
    # # Class Profiles
    # principal.permissions.add(Permission.objects.get(name='Can add class profile'))
    # principal.permissions.add(Permission.objects.get(name='Can change class profile'))
    # principal.permissions.add(Permission.objects.get(name='Can delete class profile'))
    # principal.permissions.add(Permission.objects.get(name='Can view class profile'))
    # # Principals
    # principal.permissions.add(Permission.objects.get(name='Can add principal'))
    # principal.permissions.add(Permission.objects.get(name='Can change principal'))
    # principal.permissions.add(Permission.objects.get(name='Can delete principal'))
    # principal.permissions.add(Permission.objects.get(name='Can view principal'))
    # # Teachers
    # principal.permissions.add(Permission.objects.get(name='Can add teacher'))
    # principal.permissions.add(Permission.objects.get(name='Can change teacher'))
    # principal.permissions.add(Permission.objects.get(name='Can delete teacher'))
    # principal.permissions.add(Permission.objects.get(name='Can view teacher'))
    # # Parents
    # principal.permissions.add(Permission.objects.get(name='Can add parent'))
    # principal.permissions.add(Permission.objects.get(name='Can change parent'))
    # principal.permissions.add(Permission.objects.get(name='Can delete parent'))
    # principal.permissions.add(Permission.objects.get(name='Can view parent'))
    # # Students
    # principal.permissions.add(Permission.objects.get(name='Can add student'))
    # principal.permissions.add(Permission.objects.get(name='Can change student'))
    # principal.permissions.add(Permission.objects.get(name='Can delete student'))
    # principal.permissions.add(Permission.objects.get(name='Can view student'))
    # principal.save()
    teacher, created = Group.objects.get_or_create(name='Teachers')
    parents, created = Group.objects.get_or_create(name='Parents')
    students, created = Group.objects.get_or_create(name='Students')

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
