# Generated by Django 3.2.6 on 2021-08-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210803_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='members',
            field=models.ManyToManyField(to='school.Student'),
        ),
    ]
