# Generated by Django 3.2.6 on 2021-08-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210809_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
    ]
