# Generated by Django 3.2.6 on 2021-08-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_lessontable_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='squad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_class', to='school.squad'),
            preserve_default=False,
        ),
    ]
