# Generated by Django 3.2.6 on 2021-08-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_timetable_squad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
        migrations.CreateModel(
            name='SquadSubjects',
            fields=[
                ('squad_subject', models.AutoField(primary_key=True, serialize=False)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadsubjects_class', to='school.squad')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadsubjects_subject', to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadsubjects_teacher', to='school.teacher')),
            ],
            options={
                'db_table': 'squad_subjects',
            },
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_subject', to='school.squadsubjects'),
        ),
    ]
