# Generated by Django 3.2.6 on 2021-08-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='squad',
        ),
    ]
