# Generated by Django 3.2.6 on 2021-08-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20210815_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('SP', 'Spóźnienie'), ('NB', 'Nieobecność'), ('NU', 'Nieobecność usprawiedliwiona')], max_length=2)),
                ('date', models.DateField(auto_now_add=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_edited_by', to='school.teacher')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_issued_by', to='school.teacher')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_lesson_number', to='school.lessontable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_student', to='school.student')),
            ],
            options={
                'db_table': 'attendance_events',
            },
        ),
    ]
