# Generated by Django 3.2.6 on 2021-08-03 15:35

from django.contrib.auth.models import Group, Permission
from django.db import migrations

def create_default_groups(apps, schema_editor):
    principal = Group.objects.get_or_create(name='Principals')
    teacher = Group.objects.get_or_create(name='Teachers')
    parents = Group.objects.get_or_create(name='Parents')
    students = Group.objects.get_or_create(name='Students')

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
