# Generated by Django 3.2.6 on 2021-08-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210807_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='year_end',
            field=models.IntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='squad',
            name='year_start',
            field=models.IntegerField(default=2021),
        ),
    ]
