# Generated by Django 3.2.6 on 2021-08-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20210810_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classprofile',
            old_name='class_profile',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='lessontable',
            old_name='lesson_table',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='squad',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='squadsubject',
            old_name='squad_subject',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='studentparent',
            old_name='student_parent',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='time_table',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('M', 'Poniedziałek'), ('T', 'Wtorek'), ('W', 'Środa'), ('C', 'Czwartek'), ('F', 'Piątek')], max_length=1),
        ),
    ]
