# Generated by Django 3.2.6 on 2021-08-31 13:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0017_auto_20210825_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=2048)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payevent_creator', to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payevent_squad', to='school.squad')),
            ],
            options={
                'db_table': 'pay_event',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_event', to='school.payevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_target', to='school.student')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
