# Generated by Django 3.2.6 on 2021-08-31 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_myuser_payevent_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payevent',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payevent_squad', to='school.squad'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
